export const COLOR_DANGER = 'COLOR_DANGER';
export const COLOR_DEFAULT = 'COLOR_DEFAULT';
export const COLOR_SUCCESS = 'COLOR_SUCCESS';

export type T_COLOR_DANGER = 'COLOR_DANGER';
export type T_COLOR_DEFAULT = 'COLOR_DEFAULT';
export type T_COLOR_SUCCESS = 'COLOR_SUCCESS';
export type T_COLOR = T_COLOR_DANGER | T_COLOR_DEFAULT | T_COLOR_SUCCESS;
